apiVersion: v1
kind: Service
metadata:
  name: accounting-service
  namespace: default
spec:
  selector:
    app: accounting-ms
  ports:
    - port: 2025
      targetPort: 2025
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accounting-ms-cluster
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: accounting-ms
    spec:
      containers:
      - name: fineract-cn-accounting
        image: apache/fineract-cn-accounting:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: external-tools-config
          - configMapRef:
              name: fineract-service-config
        env:
          - name: eureka.instance.hostname
            value: accounting-ms
          - name: server.port
            value: "2025"
          - name: spring.application.name
            value:  accounting-v1
          - name: system.publicKey.modulus
            valueFrom:
              configMapKeyRef:
                key: PUBLIC_KEY_MODULUS
                name: secret-config
          - name: system.publicKey.exponent
            valueFrom:
              configMapKeyRef:
                key: PUBLIC_KEY_EXPONENT
                name: secret-config
          - name: system.publicKey.timestamp
            valueFrom:
              configMapKeyRef:
                key: PUBLIC_KEY_TIMESTAMP
                name: secret-config
          - name: system.privateKey.modulus
            valueFrom:
              configMapKeyRef:
                key: PRIVATE_KEY_MODULUS
                name: secret-config
          - name: system.privateKey.exponent
            valueFrom:
              configMapKeyRef:
                key: PRIVATE_KEY_EXPONENT
                name: secret-config
        ports:
          - containerPort: 2025
