{{- if .Values.customer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: customer-ms
  ports:
    - port: 2024
      targetPort: 2024
  # type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-ms-cluster
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: customer-ms
    spec:
      containers:
      - name: customer-ms
        image: {{ .Values.customer.image }}
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: external-tools-config
          - configMapRef:
              name: fineract-service-config
        env:
          - name: kubernetes.service.name
            value: customer-service
          - name: server.port
            value: "2024"
          - name: spring.application.name
            value:  customer-v1
          - name: system.publicKey.modulus
            valueFrom:
              configMapKeyRef:
                key: PUBLIC_KEY_MODULUS
                name: secret-config
          - name: system.publicKey.exponent
            valueFrom:
              configMapKeyRef:
                key: PUBLIC_KEY_EXPONENT
                name: secret-config
          - name: system.publicKey.timestamp
            valueFrom:
              configMapKeyRef:
                key: PUBLIC_KEY_TIMESTAMP
                name: secret-config
          - name: system.privateKey.modulus
            valueFrom:
              configMapKeyRef:
                key: PRIVATE_KEY_MODULUS
                name: secret-config
          - name: system.privateKey.exponent
            valueFrom:
              configMapKeyRef:
                key: PRIVATE_KEY_EXPONENT
                name: secret-config
        ports:
          - containerPort: 2024
{{- end }}