{{- if .Values.portfolio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: portfolio-ms
  ports:
    - port: 2026
      targetPort: 2026
  # type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-ms-cluster
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: portfolio-ms
    spec:
      containers:
      - name: portfolio-ms
        image: {{ .Values.portfolio.image }}
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: external-tools-config
          - configMapRef:
              name: fineract-service-config
        env:
          - name: kubernetes.service.name
            value: portfolio-service
          - name: server.port
            value: "2026"
          - name: spring.application.name
            value:  portfolio-v1
          - name: system.publicKey.modulus
            valueFrom:
              configMapKeyRef:
                key: PUBLIC_KEY_MODULUS
                name: secret-config
          - name: system.publicKey.exponent
            valueFrom:
              configMapKeyRef:
                key: PUBLIC_KEY_EXPONENT
                name: secret-config
          - name: system.publicKey.timestamp
            valueFrom:
              configMapKeyRef:
                key: PUBLIC_KEY_TIMESTAMP
                name: secret-config
          - name: system.privateKey.modulus
            valueFrom:
              configMapKeyRef:
                key: PRIVATE_KEY_MODULUS
                name: secret-config
          - name: system.privateKey.exponent
            valueFrom:
              configMapKeyRef:
                key: PRIVATE_KEY_EXPONENT
                name: secret-config
        ports:
          - containerPort: 2026
{{- end }}